Repository Neupinion/Neupinion-App, pull requests merged in 2024-02, with the labels that each got.

#11 Feat/#8 카테고리 1,2 UI 제작
  app.json
  src/features/remakeissue/components/CategoryItem.tsx
  src/features/remakeissue/components/CategorySlider.tsx
  src/pages/TestPage.tsx
  src/shared/styles/GlobalTextStyles.ts
  tsconfig.json
Labels: ✨ Feature, 🚀 FrontEnd

#22 Feat/#21 메인페이지 컴포넌트 제작 및 데이터 타입 정의
  App.tsx
  package-lock.json
  package.json
  src/assets/icon/mainarrow.svg
  src/assets/icon/mainsearch.svg
  src/assets/icon/mainuser.svg
  src/dummy/FollowUpIssueDummy.ts
  src/dummy/ReProcessedIssueDummy.ts
  src/features/remakeissue/components/FakeIssueIcon.tsx
  src/features/remakeissue/components/FakeIssueItem.tsx
  src/features/remakeissue/components/FakeIssueSlider.tsx
  src/features/remakeissue/components/Indicator.tsx
  src/pages/MainPage.tsx
  src/shared/styles/GlobalTextStyles.ts
  src/shared/types/custom.d.ts
  src/shared/types/news.ts
Labels: ✨ Feature, 🚀 FrontEnd

#28 Feat/#20 svg 아이콘 추가 및, 제목 최대치 지정
  src/features/remakeissue/components/FakeIssueIcon.tsx
  src/features/remakeissue/components/FakeIssueItem.tsx
Labels: 🚀 FrontEnd, 🛠️ Refactor

#25 Feat/#19 후속이슈 UI제작 및 Api 연동
  .eslintrc.js
  babel.config.js
  env.d.ts
  package-lock.json
  package.json
  src/features/date/DateProvider.tsx
  src/features/followupissue/components/FollowUpIssueContainer.tsx
  src/features/followupissue/components/FollowUpIssueItem.tsx
  src/features/followupissue/components/FollowUpIssueSlider.tsx
  src/features/followupissue/constants/invisibleFollowUpData.ts
  src/features/followupissue/functions/getMainCategoryName.ts
  src/features/followupissue/functions/getSubCategoryName.ts
  src/features/followupissue/remotes/followupissue.ts
  src/shared/hooks/useFetch.ts
  src/shared/remotes/axios.ts
  src/shared/styles/theme.ts
  src/shared/types/errorResponse.ts
Labels: ✨ Feature, 🚀 FrontEnd

#17 Feat/#13 달력 UI 구현
  package-lock.json
  package.json
  src/dateSelect/components/DateModal.tsx
  src/dateSelect/constants/cvtParamDate.ts
  src/dateSelect/constants/locales.ts
Labels: ✨ Feature, 🚀 FrontEnd

#31 Feat/#27 재가공 이슈, 후속이슈 api 연동 및 날짜 상태관리
  App.tsx
  app.json
  package-lock.json
  package.json
  src/assets/icon/datemodalclose.svg
  src/assets/icon/rightarrow.svg
  src/dummy/FollowUpIssueDummy.ts
  src/features/date/components/DateModal.tsx
  src/features/date/constants/cvtParamDate.ts
  src/features/date/constants/locales.ts
  src/features/date/functions/formatDate.ts
  src/features/date/provider/DateProvider.tsx
  src/features/followupissue/components/FollowUpIssueContainer.tsx
  src/features/followupissue/components/FollowUpIssueItem.tsx
  src/features/followupissue/components/FollowUpIssueSlider.tsx
  src/features/followupissue/functions/getSubCategoryName.ts
  src/features/remakeissue/components/AfterIssueItem.tsx
  src/features/remakeissue/components/AfterIssueSlider.tsx
  src/features/remakeissue/components/CategoryItem.tsx
  src/features/remakeissue/components/CategorySlider.tsx
  src/features/remakeissue/components/FakeIssueIcon.tsx
  src/features/remakeissue/components/FakeIssueItem.tsx
  src/features/remakeissue/components/FakeIssueSlider.tsx
  src/features/remakeissue/components/Indicator.tsx
  src/features/remakeissue/remotes/reprocessedissue.ts
  src/pages/MainPage.tsx
  src/pages/TestPage.tsx
  src/shared/styles/GlobalTextStyles.ts
Labels: ✨ Feature, 🚀 FrontEnd, 🛠️ Refactor
