Repository Neupinion/Neupinion-App, pull requests merged in 2024-04, with the labels that each got.

#73 Bug/#73 expo-font 버전 재관리로 수정
  package-lock.json
  package.json
Labels: 🚀 FrontEnd, 🪰Bug

#71 Feat/#70 의견쓰기 활동의 api 연동
  .eslintrc.js
  src/dummy/OpinionPinSentenceDummy.ts
  src/dummy/OpinionWriteDummy.ts
  src/features/opinion/components/OpinionEvaluateCredibility.tsx
  src/features/opinion/components/OpinionPinIssue.tsx
  src/features/opinion/components/OpinionWriteBottomSheet.tsx
  src/features/opinion/components/OpinionWriteContainer.tsx
  src/features/opinion/components/PinButton.tsx
  src/features/opinion/components/PinTextNumberContainer.tsx
  src/features/opinion/components/SentenceBox.tsx
  src/features/opinion/functions/opinionElementExtractFunction.ts
  src/features/opinion/remotes/opinion.ts
  src/features/remakeissue/components/OpinionWriteSlider.tsx
  src/features/remakeissue/remotes/reprocessedissue.ts
  src/pages/DetailPage.tsx
  src/pages/OpinionPinPage.tsx
  src/pages/OpinionPostPage.tsx
  src/rootStackParamList.ts
  src/shared/components/WarningModal.tsx
  src/shared/hooks/useFetch.ts
  src/shared/types/news.ts
Labels: ✨ Feature, 🚀 FrontEnd

#67 Feat/#62 상세페이지 api 구현
  package-lock.json
  package.json
  src/Navigation.tsx
  src/assets/icon/moon1.svg
  src/assets/icon/opinionCard.svg
  src/assets/icon/pin.svg
  src/features/remakeissue/components/CategoryLatestNews.tsx
  src/features/remakeissue/components/CategoryLatestNewsItem.tsx
  src/features/remakeissue/components/FakeIssueItem.tsx
  src/features/remakeissue/components/FakeIssueSlider.tsx
  src/features/remakeissue/components/OpinionWriteSlider.tsx
  src/features/remakeissue/components/ReliabilityEvaluation.tsx
  src/features/remakeissue/components/ReprocessedIssueContentsSlider.tsx
  src/features/remakeissue/constants/newsCategoryMapping.ts
  src/features/remakeissue/constants/reliabilty.ts
  src/features/remakeissue/remotes/opinionWrite.ts
  src/features/remakeissue/remotes/reprocessedIssueContent.ts
  src/features/remakeissue/remotes/sameCategoryReprocessedIssue.ts
  src/features/remakeissue/remotes/submitVoteResult.ts
  src/features/remakeissue/remotes/toggleBookmark.ts
  src/pages/MainPage.tsx
  src/pages/ReprocessedIssueDetailPage.tsx
  src/rootStackParamList.ts
  src/shared/styles/theme.ts
  src/shared/types/news.ts
Labels: 🚀 FrontEnd
