Repository Neupinion/Neupinion-App, pull requests merged in 2024-06, with the labels that each got.

#117 feat: 메인페이지 워딩 변경 및 top5의 견 위치 수정
  src/features/vote/components/TopOpinionSlider.tsx
  src/pages/MainPage.tsx
  src/pages/OpinionMainPage.tsx
  src/pages/ReprocessedIssueDetailPage.tsx
Labels: ✨ Feature, 🚀 FrontEnd

#103 Feat/#96 스플래시 화면 적용 및 구글 소셜로그인 구현
  App.tsx
  app.json
  assets/icon.png
  env.d.ts
  package-lock.json
  package.json
  src/Navigation.tsx
  src/assets/icon/appleicon.svg
  src/assets/icon/googleicon.svg
  src/assets/icon/kakaologo.svg
  src/assets/icon/neuplogin.svg
  src/assets/splash/first_splash.png
  src/assets/splash/second_splash.png
  src/assets/splash/third_splash.png
  src/features/auth/constants/appTextIconSize.ts
  src/features/auth/constants/googleOAuthUri.ts
  src/features/auth/constants/socialAuth.ts
  src/features/auth/constants/userAgent.ts
  src/features/auth/remotes/googleLogin.ts
  src/features/auth/types/accessToken.ts
  src/features/remakeissue/components/Indicator.tsx
  src/features/splash/constants/splashData.ts
  src/features/splash/types/splashDataItem.ts
  src/pages/LoginPage.tsx
  src/pages/SplashPage.tsx
  src/recoil/webViewState.ts
  src/rootStackParamList.ts
  src/shared/remotes/axios.ts
  src/shared/types/tokenResponse.ts
  src/shared/types/userToken.ts
  src/shared/types/webView.ts
  src/useCachedResources.ts
Labels: ✨ Feature

#95 Feat/#94 편향키워드 버블차트, 사용자리포트 UI팝업을 제작한다.
  src/assets/.DS_Store
  src/assets/icon/popupclosebutton.svg
  src/dummy/KeyWordDummy.ts
  src/features/issuereport/componenets/ColorBubble.tsx
  src/features/issuereport/componenets/ReportBubbleChart.tsx
  src/features/issuereport/componenets/ReportBubbleChartContainer.tsx
  src/features/issuereport/componenets/ReportContainer.tsx
  src/features/issuereport/constants/bubbleColor.ts
  src/features/issuereport/function/getBubbleFontSize.ts
  src/features/issuereport/function/processApiResponse.ts
  src/features/issuereport/remotes/getIssueKeyword.ts
  src/features/issuereport/type/keyword.ts
  src/features/remakeissue/components/Indicator.tsx
  src/pages/ReprocessedIssueDetailPage.tsx
Labels: ✨ Feature, 🚀 FrontEnd

#123 Refactor/#122 스플래시 이미지 페이지 스크롤 수정
  src/pages/SplashPage.tsx
Labels: 🚀 FrontEnd, 🛠️ Refactor

#126 Refactor/#120 로그인 기능 수정, 버블차트 스타일 수정, 신고 팝업 제작
  src/features/auth/constants/userAgent.ts
  src/features/auth/remotes/googleLogin.ts
  src/features/issuereport/componenets/ColorBubble.tsx
  src/features/issuereport/componenets/ReportBubbleChart.tsx
  src/features/issuereport/componenets/ReportBubbleChartContainer.tsx
  src/features/issuereport/componenets/ReportContainer.tsx
  src/features/issuereport/constants/bubbleFontSize.ts
  src/features/issuereport/function/getBubbleFontSize.ts
  src/features/issuereport/function/processApiResponse.ts
  src/features/issuereport/remotes/getIssueKeyword.ts
  src/features/opinion/components/OpinionPinIssue.tsx
  src/features/opinion/components/OpinionPostCheckButton.tsx
  src/features/opinion/components/OpinionWriteBottomSheet.tsx
  src/features/remakeissue/components/OpinionWriteSlider.tsx
  src/features/remakeissue/components/ReprocessedIssueContentsSlider.tsx
  src/features/vote/components/TopOpinionSlider.tsx
  src/pages/LoginPage.tsx
  src/pages/OpinionMainPage.tsx
  src/pages/OpinionPinPage.tsx
  src/pages/ReprocessedIssueDetailPage.tsx
  src/shared/components/Opinion/OpinionPaper.tsx
  src/shared/components/ReportModal.tsx
Labels: ✨ Feature, 🚀 FrontEnd, 🪰Bug, 🛠️ Refactor

#137 Feat/#114 좋아요 API 구현
  App.tsx
  src/Navigation.tsx
  src/assets/icon/favoritefull.svg
  src/dummy/KeyWordDummy.ts
  src/features/auth/remotes/googleLogin.ts
  src/features/auth/types/accessToken.ts
  src/features/opinion/components/OpinionMainPageComponents/ParagraphOpinionCard.tsx
  src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCard.tsx
  src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCategory.tsx
  src/features/opinion/components/OpinionWriteBottomSheet.tsx
  src/features/opinion/components/SentenceBox.tsx
  src/features/opinion/remotes/opinion.ts
  src/features/remakeissue/components/FakeIssueItem.tsx
  src/features/remakeissue/components/Indicator.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/OpinionByParagraphPage.tsx
  src/pages/ReprocessedIssueDetailPage.tsx
Labels: 🚀 FrontEnd, 🛠️ Refactor

#130 Feat/#128 의견 쓰기 페이지에서, 필수 요소가 입력되지 않았을 때의 토스트를 제작한다
  App.tsx
  src/assets/icon/warntoast.svg
  src/features/opinion/components/OpinionPostCheckButton.tsx
  src/shared/components/toast/Toast.tsx
  src/shared/components/toast/ToastContext.tsx
Labels: ✨ Feature, 🚀 FrontEnd

#138 Refactor/#134 api 수정 및 재가공 이슈 ui 수정
  app.json
  src/dummy/FollowUpIssueDummy.ts
  src/features/date/components/MainPageHeader.tsx
  src/features/issuereport/componenets/ReportContainer.tsx
  src/features/opinion/components/OpinionMainPageComponents/ParagraphOpinionCard.tsx
  src/features/opinion/components/OpinionWriteBottomSheet.tsx
  src/features/remakeissue/components/CategoryItem.tsx
  src/features/remakeissue/components/CategoryLatestNews.tsx
  src/features/remakeissue/components/CategoryLatestNewsItem.tsx
  src/features/remakeissue/components/ReliabilityEvaluation.tsx
  src/features/remakeissue/remotes/submitVoteResult.ts
  src/features/splash/constants/splashData.ts
  src/features/totalvote/components/BarGraph.tsx
  src/features/totalvote/components/TimeLine.tsx
  src/features/totalvote/components/TotalVoteChartContainer.tsx
  src/features/totalvote/types/integratedResult.ts
  src/features/vote/components/BubbleChart.tsx
  src/features/vote/components/FollowUpIssueSlider.tsx
  src/features/vote/components/GradientBubble.tsx
  src/features/vote/components/RelatedIssues.tsx
  src/features/vote/components/TopOpinionSlider.tsx
  src/features/vote/components/VoteBubbleChart.tsx
  src/features/vote/components/VoteChartContainer.tsx
  src/features/vote/components/VoteRankContainer.tsx
  src/features/vote/constants/bubbleChartSize.ts
  src/features/vote/constants/bubbleColor.ts
  src/features/vote/constants/bubbleGradient.ts
  src/features/vote/constants/rankConstants.ts
  src/features/vote/types/bubbleChartData.ts
  src/pages/MainPage.tsx
  src/pages/OpinionMainPage.tsx
  src/pages/ReprocessedIssueDetailPage.tsx
  src/pages/TotalVoteResultPage.tsx
  src/pages/VoteResultPage.tsx
  src/shared/components/Opinion/OpinionPaper.tsx
  src/shared/types/news.ts
  src/shared/utils/asyncstorage/storageItem.ts
  tests/navigationService.test.ts
Labels: 🚀 FrontEnd, 🛠️ Refactor
