Repository Neupinion/Neupinion-App, pull requests merged in 2024-05, with the labels that each got.

#81 Feat/#76 재가공이슈 투표 페이지 Bubble Chart 개발 및 공통 컴포넌트 개발
  babel.config.js
  package-lock.json
  package.json
  src/Navigation.tsx
  src/assets/icon/fulldoubtvote.svg
  src/assets/icon/fulltrustvote.svg
  src/assets/icon/littledoubtvote.svg
  src/assets/icon/littletrustvote.svg
  src/dummy/TopOpinionDummy.ts
  src/dummy/VotedDataDummy.ts
  src/features/date/components/DateModal.tsx
  src/features/followupissue/components/FollowUpIssueContainer.tsx
  src/features/followupissue/components/FollowUpIssueItem.tsx
  src/features/followupissue/components/FollowUpIssueSlider.tsx
  src/features/opinion/components/OpinionPinIssue.tsx
  src/features/opinion/components/OpinionWriteBottomSheet.tsx
  src/features/remakeissue/components/AfterIssueItem.tsx
  src/features/remakeissue/components/AfterIssueSlider.tsx
  src/features/remakeissue/components/CategoryLatestNews.tsx
  src/features/remakeissue/components/CategoryLatestNewsItem.tsx
  src/features/remakeissue/components/CategorySlider.tsx
  src/features/remakeissue/components/FakeIssueIcon.tsx
  src/features/remakeissue/components/FakeIssueSlider.tsx
  src/features/remakeissue/components/OpinionWriteSlider.tsx
  src/features/remakeissue/components/ReliabilityEvaluation.tsx
  src/features/remakeissue/components/ReprocessedIssueContentsSlider.tsx
  src/features/remakeissue/constants/cardAniSize.ts
  src/features/vote/components/BubbleChart.tsx
  src/features/vote/components/GradientBubble.tsx
  src/features/vote/components/TopOpinionSlider.tsx
  src/features/vote/components/VoteChartContainer.tsx
  src/features/vote/components/VoteRankContainer.tsx
  src/features/vote/constants/bubbleChartSize.ts
  src/features/vote/constants/bubbleColor.ts
  src/features/vote/constants/bubbleGradient.ts
  src/features/vote/constants/rankConstants.ts
  src/features/vote/functions/getBubbleFontSize.ts
  src/features/vote/remotes/reprocessedIssueVote.ts
  src/features/vote/remotes/topOpinion.ts
  src/features/vote/types/bubbleChartData.ts
  src/features/vote/types/bubbleGradient.ts
  src/features/vote/types/opinion.ts
  src/pages/MainPage.tsx
  src/pages/OpinionPinPage.tsx
  src/pages/OpinionPostPage.tsx
  src/pages/ReprocessedIssueDetailPage.tsx
  src/pages/VoteResultPage.tsx
  src/rootStackParamList.ts
  src/shared/components/PageHeader.tsx
  src/shared/constants/bottomSheetAnimation.ts
  src/shared/constants/display.ts
  src/shared/styles/theme.ts
  src/shared/utils/formatNumber.ts
Labels: ✨ Feature, 🚀 FrontEnd

#83 Release Vote Result 스프린트 종료
  babel.config.js
  package-lock.json
  package.json
  src/Navigation.tsx
  src/assets/icon/fulldoubtvote.svg
  src/assets/icon/fulltrustvote.svg
  src/assets/icon/littledoubtvote.svg
  src/assets/icon/littletrustvote.svg
  src/dummy/TopOpinionDummy.ts
  src/dummy/VotedDataDummy.ts
  src/features/date/components/DateModal.tsx
  src/features/followupissue/components/FollowUpIssueContainer.tsx
  src/features/followupissue/components/FollowUpIssueItem.tsx
  src/features/followupissue/components/FollowUpIssueSlider.tsx
  src/features/opinion/components/OpinionPinIssue.tsx
  src/features/opinion/components/OpinionWriteBottomSheet.tsx
  src/features/remakeissue/components/AfterIssueItem.tsx
  src/features/remakeissue/components/AfterIssueSlider.tsx
  src/features/remakeissue/components/CategoryLatestNews.tsx
  src/features/remakeissue/components/CategoryLatestNewsItem.tsx
  src/features/remakeissue/components/CategorySlider.tsx
  src/features/remakeissue/components/FakeIssueIcon.tsx
  src/features/remakeissue/components/FakeIssueSlider.tsx
  src/features/remakeissue/components/OpinionWriteSlider.tsx
  src/features/remakeissue/components/ReliabilityEvaluation.tsx
  src/features/remakeissue/components/ReprocessedIssueContentsSlider.tsx
  src/features/remakeissue/constants/cardAniSize.ts
  src/features/vote/components/BubbleChart.tsx
  src/features/vote/components/GradientBubble.tsx
  src/features/vote/components/TopOpinionSlider.tsx
  src/features/vote/components/VoteChartContainer.tsx
  src/features/vote/components/VoteRankContainer.tsx
  src/features/vote/constants/bubbleChartSize.ts
  src/features/vote/constants/bubbleColor.ts
  src/features/vote/constants/bubbleGradient.ts
  src/features/vote/constants/rankConstants.ts
  src/features/vote/functions/getBubbleFontSize.ts
  src/features/vote/remotes/reprocessedIssueVote.ts
  src/features/vote/remotes/topOpinion.ts
  src/features/vote/types/bubbleChartData.ts
  src/features/vote/types/bubbleGradient.ts
  src/features/vote/types/opinion.ts
  src/pages/MainPage.tsx
  src/pages/OpinionPinPage.tsx
  src/pages/OpinionPostPage.tsx
  src/pages/ReprocessedIssueDetailPage.tsx
  src/pages/VoteResultPage.tsx
  src/rootStackParamList.ts
  src/shared/components/PageHeader.tsx
  src/shared/constants/bottomSheetAnimation.ts
  src/shared/constants/display.ts
  src/shared/styles/theme.ts
  src/shared/utils/formatNumber.ts
Labels: ✨ Feature, 🚀 FrontEnd

#88 Bug/#77 의견 쓰기 페이지, 버튼 오류 수정 및 핀 찍기 페이지 이슈 수정
  src/features/opinion/components/OpinionEvaluateCredibility.tsx
  src/features/opinion/components/SentenceBox.tsx
  src/pages/OpinionPinPage.tsx
Labels: ✨ Feature, 🚀 FrontEnd

#92 Feat/#91 투표 페이지 및 통합 투표 페이지 API 연동
  src/dummy/TotalVotedDataDummy.ts
  src/features/remakeissue/constants/formatDate.ts
  src/features/totalvote/components/BarGraph.tsx
  src/features/totalvote/components/TimeLine.tsx
  src/features/totalvote/components/TotalVoteChartContainer.tsx
  src/features/totalvote/remotes/getIntegratedResult.ts
  src/features/totalvote/remotes/getTimeLineIssues.ts
  src/features/totalvote/types/integratedResult.ts
  src/features/totalvote/types/timeLine.ts
  src/features/vote/components/FollowUpIssueSlider.tsx
  src/features/vote/components/RelatedIssues.tsx
  src/features/vote/components/VoteRankContainer.tsx
  src/pages/TotalVoteResultPage.tsx
  src/pages/VoteResultPage.tsx
  src/shared/components/FollowUpIssue/FollowUpIssueCardGradient.tsx
  src/shared/functions/getNewsReportOrdinalInKorean.ts
  src/shared/functions/numberToKoreanOrdinal.ts
Labels: ✨ Feature, 🚀 FrontEnd

#93 Refactor/#79 재가공이슈 상세페이지 포스트잇 및 투표 컴포넌트 UI 개선 및 바텀시트 UI 개선
  src/features/opinion/components/OpinionWriteBottomSheet.tsx
  src/features/remakeissue/components/CategoryLatestNews.tsx
  src/features/remakeissue/components/OpinionWriteSlider.tsx
Labels: 🚀 FrontEnd, 🛠️ Refactor

#102 Feat/#100 의견 페이지로 이동이 가능한 라우팅을 적용한다.
  package-lock.json
  package.json
  src/Navigation.tsx
  src/dummy/FollowUpIssueDummy.ts
  src/dummy/OpinionWriteDummy.ts
  src/dummy/ReProcessedIssueDummy.ts
  src/dummy/TopOpinionDummy.ts
  src/features/date/components/DateModal.test.tsx
  src/features/followupissue/components/FollowUpIssue.test.tsx
  src/features/remakeissue/components/AfterIssueItem.test.tsx
  src/features/remakeissue/components/AfterIssueItem2.test.tsx
  src/features/remakeissue/components/AfterIssueItem3.test.tsx
  src/features/remakeissue/components/CategoryItem.test.tsx
  src/features/remakeissue/components/CategoryLatestNews.tsx
  src/features/remakeissue/components/FakeIssue.test.tsx
  src/features/vote/components/VoteChartContainer.tsx
  src/pages/OpinionPinPage.tsx
  src/pages/VoteResultPage.tsx
Labels: Release

#105 Feat/#99 투표 페이지 UI 및 관련 api 연동 마무리
  src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCard.tsx
  src/features/opinion/components/OpinionMainPageComponents/TotalOpinionCategory.tsx
  src/pages/OpinionByParagraphPage.tsx
  src/pages/OpinionMainPage.tsx
  src/pages/VoteResultPage.tsx
  src/rootStackParamList.ts
  src/shared/components/Opinion/OpinionPaper.tsx
Labels: 🚀 FrontEnd, 🛠️ Refactor

#109 CONFIG/#108 프론트엔드 CI과정 PASS를 위한 임시 테스트코드
  tests/App.test.tsx
Labels: 🚀 FrontEnd, ⚙️Config

#110 Refactor/#106 잘못된 키워드 수정 및 마크다운 '강조' 스타일 추가
  src/features/remakeissue/components/ReprocessedIssueContentsSlider.tsx
  src/features/remakeissue/constants/reliabilty.ts
  src/pages/OpinionPinPage.tsx
Labels: 🚀 FrontEnd, 🛠️ Refactor

#111 Bug/#87 backButton이 잘 눌리지 않는 현상 수정 및 의견 쓰기 페이지 리팩토링
  src/Navigation.tsx
  src/features/date/components/MainPageHeader.tsx
  src/features/opinion/components/OpinionEvaluateCredibility.tsx
  src/features/opinion/components/OpinionPostCheckButton.tsx
  src/features/opinion/components/OpinionWriteBottomSheet.tsx
  src/features/opinion/components/OpinionWriteContainer.tsx
  src/features/opinion/components/PinButton.tsx
  src/features/opinion/functions/opinionElementExtractFunction.ts
  src/features/opinion/types/opinionPost.ts
  src/features/remakeissue/components/BookmarkButton.tsx
  src/features/remakeissue/components/OpinionWriteSlider.tsx
  src/features/remakeissue/remotes/toggleBookmark.ts
  src/features/remakeissue/types/bookmark.ts
  src/pages/AppLinkTestPage.tsx
  src/pages/MainPage.tsx
  src/pages/OpinionByParagraphPage.tsx
  src/pages/OpinionMainPage.tsx
  src/pages/OpinionPinPage.tsx
  src/pages/OpinionPostPage.tsx
  src/pages/ReprocessedIssueDetailPage.tsx
  src/pages/TotalVoteResultPage.tsx
  src/pages/VoteResultPage.tsx
  src/recoil/bookmarkState.ts
  src/recoil/issueState.ts
  src/recoil/opinionPostState.ts
  src/rootStackParamList.ts
  src/shared/components/CustomHeader.tsx
  src/shared/components/PageHeader.tsx
  src/shared/components/applink/AppLinkButton.tsx
  src/shared/constants/appLink.ts
Labels: 🚀 FrontEnd, 🪰Bug, 🛠️ Refactor
