Repository Neupinion/Neupinion-App, pull requests merged in 2024-03, with the labels that each got.

#40 Feat/#37 달력 모달의 기능을 추가, 달력 컴포넌트의 테스트 코드를 작성
  __tests__/App.test.tsx
  __tests__/__snapshots__/App.test.tsx.snap
  package-lock.json
  package.json
  src/features/date/components/DateModal.test.tsx
  src/features/date/components/DateModal.tsx
  src/features/date/constants/modalAnimationNumber.ts
  src/features/date/constants/toDashDate.ts
  src/features/followupissue/components/FollowUpIssue.test.tsx
  src/features/followupissue/components/FollowUpIssueItem.tsx
  src/features/followupissue/components/FollowUpIssueSlider.tsx
  src/features/remakeissue/components/FakeIssue.test.tsx
  src/features/remakeissue/components/FakeIssueItem.tsx
  src/features/remakeissue/components/FakeIssueSlider.tsx
  src/features/remakeissue/components/Indicator.tsx
  src/pages/MainPage.tsx
Labels: ✨ Feature, 🚀 FrontEnd

#45 Config/#18 프로젝트에 폰트를 적용할 수 있도록 한다.
  App.tsx
  package-lock.json
  package.json
  src/assets/fonts/Pretendard-Black.ttf
  src/assets/fonts/Pretendard-Bold.ttf
  src/assets/fonts/Pretendard-ExtraBold.ttf
  src/assets/fonts/Pretendard-ExtraLight.ttf
  src/assets/fonts/Pretendard-Light.ttf
  src/assets/fonts/Pretendard-Medium.ttf
  src/assets/fonts/Pretendard-Regular.ttf
  src/assets/fonts/Pretendard-SemiBold.ttf
  src/assets/fonts/Pretendard-Thin.ttf
  src/pages/MainPage.tsx
  src/shared/styles/GlobalTextStyles.ts
  src/shared/styles/fontFamily.ts
  src/useCachedResources.ts
Labels: 🚀 FrontEnd, ⚙️Config

#39 Feat/#36 새로운 후속보도 및 카테고리 카드 testcode 작성
  package-lock.json
  package.json
  src/features/remakeissue/components/AfterIssueItem.test.tsx
  src/features/remakeissue/components/AfterIssueItem.tsx
  src/features/remakeissue/components/AfterIssueItem2.test.tsx
  src/features/remakeissue/components/AfterIssueItem3.test.tsx
  src/features/remakeissue/components/AfterIssueSlider.tsx
  src/features/remakeissue/components/CategoryItem.test.tsx
  src/pages/MainPage.tsx
Labels: 🚀 FrontEnd

#56 FIX Feat/#36 오류 발생하는 테스트 수정
  src/features/remakeissue/components/AfterIssueItem.test.tsx
  src/features/remakeissue/components/AfterIssueItem2.test.tsx
  src/features/remakeissue/components/AfterIssueSlider.tsx
Labels: 🪰Bug

#58 Feat/#43-2 상세페이지-> 의견쓰기 -> 핀 찍기의 기능을 개발한다.
  App.tsx
  package-lock.json
  package.json
  src/Navigation.tsx
  src/assets/icon/opinionbackbutton.svg
  src/assets/icon/opinioninfoicon.svg
  src/assets/icon/opinionpin.svg
  src/assets/icon/opinionpurplecheck.svg
  src/dummy/OpinionPinSentenceDummy.ts
  src/features/opinionpost/components/OpinionEvaluateCredibility.tsx
  src/features/opinionpost/components/OpinionPinIssue.tsx
  src/features/opinionpost/components/OpinionWriteContainer.tsx
  src/features/opinionpost/components/PinButton.tsx
  src/features/opinionpost/components/PinTextNumberContainer.tsx
  src/features/opinionpost/components/SentenceBox.tsx
  src/pages/OpinionPinPage.tsx
  src/pages/OpinionPostPage.tsx
  src/rootStackParamList.ts
Labels: ✨ Feature, 🚀 FrontEnd

#59 Feat/#53-2 앱 공유 기능을 개발한다.
  src/pages/AppLinkTestPage.tsx
Labels: ✨ Feature, 🚀 FrontEnd

#64 Feat/#60 의견 포스트잇 클릭시 바텀시트 등장 및 삭제 팝업 개발
  package-lock.json
  package.json
  src/Navigation.tsx
  src/assets/icon/warningpopupexclamation.svg
  src/features/opinionView/components/OpinionWriteBottomSheet.tsx
  src/features/popup/components/WarningPopup.tsx
  src/pages/DetailPage.tsx
Labels: ✨ Feature, 🚀 FrontEnd

#69 Feat/#65 ModalProvider 개발 및, dateModal, bottomSheetModal과 같은 Modal 적용 방식 수정
  App.tsx
  babel.config.js
  package-lock.json
  package.json
  src/Navigation.tsx
  src/features/date/components/DateModal.test.tsx
  src/features/date/components/DateModal.tsx
  src/features/date/constants/calendarTheme.ts
  src/features/date/constants/dateModalAnimation.ts
  src/features/opinionView/components/OpinionWriteBottomSheet.tsx
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
  src/recoil/modalState.ts
  src/shared/components/ModalContainer.tsx
  src/shared/components/WarningModal.tsx
  src/shared/constants/bottomSheetAnimation.ts
  src/shared/constants/bottomSheetGestureConstants.ts
  src/shared/functions/colorWithOpacity.ts
  src/shared/hooks/useModal.ts
  src/shared/types/modal.ts
Labels: 🚀 FrontEnd, 🛠️ Refactor
